--- 
- hosts: all
  remote_user: travitskii
  become: yes
  become_user: root
  become_method: sudo
  vars:
    server_name: "nginx"
    document_root: /var/www
    app_root: html
  tasks:
#    - name: create ansible user
#      user: 
#        name: ansible 
#        shell: /bin/bash 
#        home: /home/ansible
#    - name: copy ssh pubkey to home directory
#      authorized_key: 
#        user: ansible 
#        key: "{{ lookup('file', './ansible_pubkey') }}"
  
    - name: adding ansible user to sudoers
      lineinfile: 
        dest: /etc/sudoers 
        line: "ansible ALL=(ALL)       NOPASSWD: ALL" 
        validate: 'visudo -cf %s'
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
#        become: yes

    - name: Create
      file: path={{ document_root }}/{{ app_root }} state=directory owner=www-data group=www-data


    - name: Set up HTML file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data

    - name: copy file
      copy:
        src: ./img
        dest: /var/www/html/

    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
