
---
- name: RabbitMQ ha-all cluster
  hosts: all
  remote_user: travitskii
  become: yes
  become_user: root
  become_method: sudo 
  tasks:
    - name: Update
      apt:
       update_cache: yes
       name: python3
       name: curl
       name: gnupg
       name: apt-transport-https

    - name: "Team RabbitMQ's main signing key"
      ansible.builtin.shell: curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

    - name: "Cloudsmith: modern Erlang repository"
      ansible.builtin.shell: curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

    - name: "Cloudsmith: RabbitMQ repository"
      ansible.builtin.shell: curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg > /dev/null

#    - name: "Добавление репозиториев"
#      template:
#      copy:
#        src: "rabbitmq.list"
#        dest: "/etc/apt/sources.list.d/rabbitmq.list"

    - name: Обновление кэша
      apt:
        update_cache: yes

    - name: Установка Erlang пакетов
      ansible.builtin.apt:
        pkg:
        - erlang-base
        - erlang-asn1
        - erlang-crypto
        - erlang-eldap
        - erlang-ftp
        - erlang-inets
        - erlang-mnesia
        - erlang-os-mon
        - erlang-parsetools
        - erlang-public-key
        - erlang-runtime-tools
        - erlang-snmp
        - erlang-ssl
        - erlang-syntax-tools
        - erlang-tftp
        - erlang-tools
        - erlang-xmerl

    - name: Установка RabbitMQ
      ansible.builtin.apt: 
        name: rabbitmq-server
        state: latest

 #   - name: Получение Erlang cookie
 #     copy:
 #       src: /var/lib/rabbitmq/.erlang.cookie
 #       dest: ./erlang_cookie
#        flat: yes
 #     when: "'main' in group_names"

    - name: Остановка службы RabbitMQ
      systemd:
        name: "rabbitmq-server.service"
        state: stopped
        enabled: yes

    - name: Получение Erlang cookie
      copy:
        src: /var/lib/rabbitmq/.erlang.cookie
        dest: ./erlang_cookie
        flat: yes
      when: "'main' in group_names"

    - name: Копирование Erlang cookie
      template:
        src: ./erlang.cookie.j2
        dest: /var/lib/rabbitmq/.erlang.cookie
        owner: rabbitmq
        group: rabbitmq
        mode: 0400
     # when: rabbitmq_create_cluster
#      copy:
#        src: ./.erlang_cookie
#        dest: /var/lib/rabbitmq/.erlang.cookie
#      when: "'replicas' in group_names"

    - name: Запуск сервиса RabbitMQ
      systemd:
        name: "rabbitmq-server.service"
        state: started
        enabled: yes

    - name: Остановка и перезагрузка приложения
      command: "rabbitmqctl "
      when:
        "stop"
#        - "reset"
      when: "'replicas' in group_names"

    - name: Правка host файлов
      lineinfile:
        dest: /etc/hosts
        regexp: .*{{ hostvars[item]['ansible_hostname'] }}.*
        line: "{{ hostvars[item]['ansible_all_ipv4_addresses'][1] }} {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_fqdn'] }}"
      with_items: "{{ groups['rabbitmq'] }}"

    - name: Присоединение нод-реплик к главной ноде
      command: "rabbitmqctl join_cluster rabbit@{{ hostvars[item]['ansible_hostname'] }}"
      when: "'replicas' in group_names"
      with_items:
        - "{{ groups['main'] }}"

    - name: Старт приложения
      command: "rabbitmqctl {{ item }}"
      when: "'replicas' in group_names"
      with_items:
        - "start_app"

    - name: Установка политики HA-ALL
      command: "rabbitmqctl {{ item }}"
      when: "'main' in group_names"
      with_items:
        - "set_policy ha-all \"\" '{\"ha-mode\":\"all\",\"ha-sync-mode\":\"automatic\"}'"
